const { contextBridge, ipcRenderer } = require('electron')

const api = {
  getConfig: () => ipcRenderer.invoke('config:get'),
  getVault: () => ipcRenderer.invoke('config:getVault'),
  getWorkspace: () => ipcRenderer.invoke('config:getWorkspace'),
  chooseWorkspace: () => ipcRenderer.invoke('config:chooseWorkspace'),
  setWorkspace: (dir) => ipcRenderer.invoke('config:setWorkspace', dir),
  chooseVault: () => ipcRenderer.invoke('config:chooseVault'),
  setVault: (dir) => ipcRenderer.invoke('config:setVault', dir),
  migrateVault: () => ipcRenderer.invoke('config:migrateVault'),
  setTheme: (theme) => ipcRenderer.invoke('config:setTheme', theme),
  setDensity: (density) => ipcRenderer.invoke('config:setDensity', density),
  setLanguage: (language) => ipcRenderer.invoke('config:setLanguage', language),
  saveAIProfile: (profile, input) => ipcRenderer.invoke('config:saveAIProfile', profile, input),
  saveGithub: (input) => ipcRenderer.invoke('config:saveGithub', input),
  aiStatus: () => ipcRenderer.invoke('config:aiStatus'),
  listProjects: () => ipcRenderer.invoke('project:list'),
  createProject: (input) => ipcRenderer.invoke('project:create', input),
  chooseProject: () => ipcRenderer.invoke('project:choose'),
  loadProject: (root) => ipcRenderer.invoke('project:load', root),
  readDoc: (filePath) => ipcRenderer.invoke('doc:read', filePath),
  saveDocBody: (filePath, data, body) => ipcRenderer.invoke('doc:saveBody', filePath, data, body),
  deleteDoc: (filePath) => ipcRenderer.invoke('doc:delete', filePath),
  openDocExternal: (filePath) => ipcRenderer.invoke('doc:openExternal', filePath),
  createDoc: (root, kind, input) => ipcRenderer.invoke('doc:create', root, kind, input),
  chooseMarkdownImport: (root) => ipcRenderer.invoke('import:chooseMarkdown', root),
  importMarkdownText: (root, markdown, title) =>
    ipcRenderer.invoke('import:markdownText', root, markdown, title),
  syncMarkdownImports: (root) => ipcRenderer.invoke('import:syncMarkdown', root),
  initPrompts: (root) => ipcRenderer.invoke('prompt:init', root),
  readPrompt: (root, name) => ipcRenderer.invoke('prompt:read', root, name),
  createAIImportPlan: (root, input) => ipcRenderer.invoke('import:aiPlan', root, input),
  loadImportSession: (root, sessionId) => ipcRenderer.invoke('import:session', root, sessionId),
  answerImportIssue: (root, sessionId, issueId, answer) =>
    ipcRenderer.invoke('import:answerIssue', root, sessionId, issueId, answer),
  landImportSession: (root, sessionId) => ipcRenderer.invoke('import:landSession', root, sessionId),
  discussCanon: (root, input) => ipcRenderer.invoke('canon:discuss', root, input),
  assembleContext: (root, sceneId) => ipcRenderer.invoke('scene:context', root, sceneId),
  assembleTargetContext: (root, target) => ipcRenderer.invoke('target:context', root, target),
  checkTarget: (root, target) => ipcRenderer.invoke('target:check', root, target),
  checkScene: (root, sceneId) => ipcRenderer.invoke('scene:check', root, sceneId),
  semanticCheckScene: (root, sceneId) => ipcRenderer.invoke('scene:semanticCheck', root, sceneId),
  checkSceneIntoRun: (root, sceneId) => ipcRenderer.invoke('scene:checkIntoRun', root, sceneId),
  generateDryRun: (root, sceneId) => ipcRenderer.invoke('scene:generateDryRun', root, sceneId),
  generate: (root, sceneId) => ipcRenderer.invoke('scene:generate', root, sceneId),
  generateOutline: (root, outlineId) => ipcRenderer.invoke('outline:generate', root, outlineId),
  buildChapterWritingPlan: (root, chapterId, selectedByScene) =>
    ipcRenderer.invoke('chapter:writingPlan', root, chapterId, selectedByScene),
  createFinalizeReviewPlan: (root, input) => ipcRenderer.invoke('finalize:reviewPlan', root, input),
  loadFinalizeReviewSession: (root, sessionId) => ipcRenderer.invoke('finalize:session', root, sessionId),
  confirmFinalizeImpact: (root, sessionId, impactId, answer, state) =>
    ipcRenderer.invoke('finalize:confirmImpact', root, sessionId, impactId, answer, state),
  readRunFile: (root, runId, file) => ipcRenderer.invoke('run:readFile', root, runId, file),
  acceptRun: (root, runId) => ipcRenderer.invoke('run:accept', root, runId),
  exportManuscript: (root, options) => ipcRenderer.invoke('export:manuscript', root, options),
  importSillyTavernCard: (root, filePath) => ipcRenderer.invoke('st:importCard', root, filePath),
  exportSillyTavernCard: (root, characterId) => ipcRenderer.invoke('st:exportCard', root, characterId),
  exportSillyTavernLorebook: (root) => ipcRenderer.invoke('st:exportLorebook', root),
  gitStatus: (root) => ipcRenderer.invoke('git:status', root),
  gitInit: (root) => ipcRenderer.invoke('git:init', root),
  gitCommit: (root, message) => ipcRenderer.invoke('git:commit', root, message),
  gitSync: (root, message) => ipcRenderer.invoke('git:sync', root, message),
  githubCreateRepoForProject: (root) => ipcRenderer.invoke('github:createRepoForProject', root),
  gitSetRemote: (root, url) => ipcRenderer.invoke('git:setRemote', root, url)
}

contextBridge.exposeInMainWorld('quillarium', api)
