import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

const generateMock = vi.hoisted(() => vi.fn())
const dialogMock = vi.hoisted(() => ({ showOpenDialog: vi.fn() }))

vi.mock('electron', () => ({
  dialog: dialogMock,
  ipcMain: { handle: vi.fn() },
  safeStorage: {
    isEncryptionAvailable: () => false,
    encryptString: (value: string) => Buffer.from(value),
    decryptString: () => ''
  }
}))

vi.mock('@quillarium/ai', async () => {
  const actual = await vi.importActual<typeof import('@quillarium/ai')>('@quillarium/ai')
  return {
    ...actual,
    generateDisplayImageCandidate: generateMock
  }
})

import {
  createIssue,
  createProjectAt,
  createWorldEntry,
  pathExists,
  readMarkdown,
  updateProjectConfig,
  writeMarkdown,
  WRITER_DEFAULT_DISPLAY_LAYER
} from '@quillarium/core'
import {
  chooseDesktopDisplayImage,
  confirmDesktopDisplayImage,
  generateDesktopDisplayImage,
  listDesktopDisplayImages
} from './display-images.js'

const PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  'base64'
)

const roots: string[] = []

beforeEach(() => {
  generateMock.mockReset()
  dialogMock.showOpenDialog.mockReset()
})

afterEach(async () => {
  vi.unstubAllEnvs()
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })))
})

async function fixture(id: string, enabled = true) {
  const root = await mkdtemp(path.join(os.tmpdir(), `quillarium-desktop-display-${id}-`))
  roots.push(root)
  vi.stubEnv('QUILL_CONFIG_DIR', path.join(root, 'config'))
  await createProjectAt(root, {
    id,
    title: id,
    display_layer: enabled ? { enabled: true, migrated: true } : WRITER_DEFAULT_DISPLAY_LAYER
  })
  const cardFile = await createWorldEntry(root, '林舟', { id: 'world-lin' }, '水手。')
  const current = await readMarkdown<Record<string, unknown>>(cardFile)
  delete current.data.image
  await writeMarkdown(cardFile, current.data, current.content)
  return { root, cardFile }
}

describe('desktop display image IPC', () => {
  it('refuses uploads when the display layer is off and does not write card image', async () => {
    const { root, cardFile } = await fixture('off', false)
    const source = path.join(root, 'lin.png')
    await writeFile(source, PNG)
    dialogMock.showOpenDialog.mockResolvedValue({ canceled: false, filePaths: [source] })

    await expect(chooseDesktopDisplayImage(root, 'world-lin', '林舟')).rejects.toThrow(
      '展示层已关闭，不能添加配图。'
    )
    expect(await pathExists(path.join(root, 'assets', 'display', 'world-lin', 'manifest.json'))).toBe(false)
    const card = await readMarkdown<Record<string, unknown>>(cardFile)
    expect(card.data).not.toHaveProperty('image')
  })

  it('uploads into the gallery without writing PlanningCardDoc.image', async () => {
    const { root, cardFile } = await fixture('upload')
    const source = path.join(root, 'lin.png')
    await writeFile(source, PNG)
    dialogMock.showOpenDialog.mockResolvedValue({ canceled: false, filePaths: [source] })

    const manifest = await chooseDesktopDisplayImage(root, 'world-lin', '林舟')
    expect(manifest?.selected_id).toBeTruthy()
    expect(manifest?.images).toHaveLength(1)
    expect(manifest?.image_data_urls[0]?.id).toBe(manifest?.selected_id)
    expect(await pathExists(path.join(root, 'assets', 'display', 'world-lin', 'manifest.json'))).toBe(true)
    const card = await readMarkdown<Record<string, unknown>>(cardFile)
    expect(card.data).not.toHaveProperty('image')
  })

  it('keeps generated bytes in memory until confirm and coerces a missing api key', async () => {
    const { root } = await fixture('generate')
    generateMock.mockResolvedValue({ bytes: new Uint8Array(PNG), mime: 'image/png' })

    const candidate = await generateDesktopDisplayImage(root, 'world-lin', '林舟\n水手。')
    expect(candidate.candidate_id).toBeTruthy()
    expect(candidate.data_url.startsWith('data:image/png;base64,')).toBe(true)
    expect(await pathExists(path.join(root, 'assets', 'display', 'world-lin', 'manifest.json'))).toBe(false)
    expect(generateMock).toHaveBeenCalledTimes(1)
    const profile = generateMock.mock.calls[0]![0].profile as { apiKey: string }
    expect(profile.apiKey).toBe('')

    const confirmed = await confirmDesktopDisplayImage(root, 'world-lin', candidate.candidate_id)
    expect(confirmed.images[0]?.source).toBe('generated')
    expect(confirmed.image_data_urls[0]?.id).toBe(confirmed.selected_id)
    expect(await listDesktopDisplayImages(root, 'world-lin')).toMatchObject({
      selected_id: confirmed.selected_id
    })
  })

  it('rejects generate for cards that cannot hold display images', async () => {
    const { root } = await fixture('issue-type')
    await createIssue(root, 'Choose POV', { id: 'issue-pov' })
    await updateProjectConfig(root, { display_layer: { enabled: true, migrated: true } })
    await expect(generateDesktopDisplayImage(root, 'issue-pov', '提示')).rejects.toThrow(
      '该卡片类型不能配图。'
    )
  })
})
